### PR TITLE
Coverage utils

### PR DESCRIPTION
**Pull request by gpaixao**
:100: % coverage utils

### CODE REVIEW

**Comment by gr2m** [comment]
This is great, thank you Guilherme 👍👏 I think this is your first contribution to Hoodie, right? Are you on twitter by chance? We like giving shoutouts to new contributors :) 

And regarding coverage: while we have 100% on line coverage now, some branches are not yet covered. What you can do to check it locally is to run tests and then coverage with the `lcov` reporter

```js
npm test
node_modules/.bin/nyc report --reporter=lcov
```

then open `coverage/lcov-report/index.html` in your browser, it will look like this:

screen shot 2016-10-17 at 10 35 40

You can click on serialise-account.js & serialise-session.js to find out what branches are not covered. Would be great if you could get these covered, too :)

**Comment by gpaixao** [comment]
Great, I'm sorry. I did thinking only in percent. I'm doing here.

**Comment by gpaixao** [comment]
I created changes in other branch, after don't see need, closed.

**Comment by gr2m** [comment]
Great work Guilherme 🙌 Are you on twitter?

**Comment by gpaixao** [comment]
Yep, @gpaixao. tks for the opportunity, love help.

**Pull request merged**
