### PR TITLE
test(routes): POST /accounts -> 401 for non-admin

### LINKED ISSUE #124: POST /accounts Add test for 401, "Session invalid" if user is not an admin
<a href="https://ti.to/hoodie/dc-meet-the-hoodies">This issue is prepared for our Meet The Hoodies event in Washington DC on March 20th</a>

### :dart: The goal

When running `npm test` then all specifications from the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#) that we implement
should be tested. Creating an account with [POST /accounts](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account-collection/create)
defines a `401` response with a `Session invalid` error message. This can occur
the currently signed in user is not an admin. We do not test that yet, and the
goal of this issue is to create this test to make sure the server behaves correctly
and does not accidentally break in future.

### :clipboard: Step by Step

- [x] claim this issue (comment below)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Implement test in [tests/integration/routes/accounts/post-accounts-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/a2a965cc38693da53865e21a720da2183265c630/tests/integration/routes/accounts/post-accounts-test.js#L66-L69). Compare tests in [tests/integration/routes/account/get-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/a2a965cc38693da53865e21a720da2183265c630/tests/integration/routes/account/get-account-test.js#L62-L95): What we need here is kinda the reverse
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): POST /accounts -> 401 for non-admin`
- [ ] Start a Pull Request. Mention `closes #124` in the description.  
      If this is your first, welcome :tada: :smile:
      [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
      on how to send a pull request
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by JayWIlsonJr**
Fixes #124

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Jay, I’m looking into this one now

**Comment by gr2m** [comment]
That is an issue @Oladele also run into today. When rebased on Ola’s latest work, I still get this error (and two more):

```
tests/integration/routes/accounts/post-accounts-test.js .. 19/25
  POST /accounts > Not an admin
  not ok returns 401 status
    +++ found                                                          
    --- wanted                                                         
    -401                                                               
    +404                                                               
    compare: ===
    at:
      line: 88
      column: 11
      file: tests/integration/routes/accounts/post-accounts-test.js
    stack: |
      tests/integration/routes/accounts/post-accounts-test.js:88:11
      node_modules/hapi/lib/connection.js:298:16
      node_modules/hapi/node_modules/shot/lib/response.js:21:32
    source: |
      t.is(response.statusCode, 401, 'returns 401 status')
```

I don’t know why the server returns a `404` error here. I’ll investigate next week, or if someone else wants to look into it, just comment :)

**Comment by bryanbierce** [comment]
Hey I'd be happy to look into this one :)

**Comment by gr2m** [comment]
thanks @bryanbierce, take it away, good luck :) Let me know if you have any questions

**Comment by bryanbierce** [comment]
@gr2m Sorry it's taken me a few days to get back to this. It is currently hitting the 404 when calling `admins.validateSession` on line 39 in `routes/accounts.js`. I tried to trace that function definition but it's not in the module. As far as I can tell it is passed into the module on the `options` object and then passed to each route when every thing is built up in `plugin/index.js`. Not sure where to go from there. Am I missing something?

**Comment by codyzu** [comment]
I might be able to help here... I'm working on the same issue for GET /accounts -> not admin.

AFAIK...
@bryanbierce you are on the right track! Checkout `plugin/index.js` and we can see the `options.admins` is set from *pouchdb-admins*.

[pouchdb-admins/lib/validate-session.js](https://github.com/hoodiehq/pouchdb-admins/blob/master/lib/validate-session.js) throws an `UNAUTHORIZED` error.

[pouchdb-errors UNAUTHORIZED ERROR](https://github.com/pouchdb/errors/blob/master/index.js#L22) has status code 404. Exactly what you found!

You can see this by adding a `console.log
 AFAIK, the 404 is pouchDB saying it can't find a document for the given sessionID. T

**Comment by codyzu** [comment]
I might be able to help here... I'm working on the same issue for GET /accounts -> not admin.

AFAIK...
@bryanbierce you are on the right track! Checkout `plugin/index.js` and we can see the `options.admins` is set from *pouchdb-admins*.

[pouchdb-admins/lib/validate-session.js](https://github.com/hoodiehq/pouchdb-admins/blob/master/lib/validate-session.js) will try to find an (admin user) by the username encoded into the sessionID. This results in a `NOT_FOUND` error.

[pouchdb-errors NOT_FOUND ERROR](https://github.com/pouchdb/errors/blob/master/index.js#L34) has status code 404. Exactly what you found!

You can verify this by adding a `console.log` statement in the catch block in `routes/accounts.js` and loging the error.

Hopefully that helps find the problem. As for the solution... My branch isn't merged yet, but if you want to see my current idea, check out my pull request #137 . Good luck!

**Comment by gr2m** [comment]
Thanks a lot for helping out @codyzu :+1:

**Comment by bryanbierce** [comment]
@codyzu Thanks a ton for that help :smile: I missed the line `23` where the db options were coming and it was totally stumping me. I have this hitting the proper errors now and the tests passing, what is the next step since this PR belongs to JayWilsonJr?

**Comment by gr2m** [comment]
@bryanbierce I’d suggest we make a separate issue / PR for the `404` issue which should be `401`. We can then rebase Jay’s work on latest master and if it passes, we can merge it in

**Comment by gr2m** [comment]
done via fd1af0f – thanks y’all :+1:

**Pull request closed without merging**
