### PR TITLE
test(routes): PATCH /accounts/{id} password update response 204

### PR DESCRIPTION
**Pull request by Taekyoon**
Changed two test statements to expect returns 204 status.

closes hoodiehq/camp#70

### CODE REVIEW

**Comment by gr2m** [comment]
Great start 👍  The test looks good as is. Next step is to actually make it pass :) You’ll need to update the `PATCH /accounts/{id}` handler: https://github.com/hoodiehq/hoodie-account-server/blob/a619d1576f37e817a456fdcba9a802950ac1c413/routes/accounts.js#L169-L198

Let us know if you have any questions. Enjoy :)

**Comment by Taekyoon** [comment]
@gr2m Hey Greg, I change this `reply(json).code(201)` statement to the below.
`reply(json).code(204)`
The test was good, so I just wonder if I can make a pull request.

**Comment by gr2m** [comment]
can you look into the failing tests? Let me know if you need any help :)

**Comment by Taekyoon** [comment]
Sure! I think I'll have some questions from failing tests

**Comment by Taekyoon** [comment]
@gr2m Hi Greg, I have a question. I got an message from test results.

'PATCH /accounts/abc4567 > changing password
  not ok test unfinished: changing password
    at:
      line: 161
      column: 11
      file: tests/integration/routes/accounts/patch-accounts-test.js
    source: |
      group.test('changing password', function (t) {'

But, I can't catch what this message says. Can you give me a hint to get over this?

**Comment by Taekyoon** [comment]
@gr2m Hi Greg, I have a question. I got an message from test results.

```
PATCH /accounts/abc4567 > changing password
  not ok test unfinished: changing password
    at:
      line: 161
      column: 11
      file: tests/integration/routes/accounts/patch-accounts-test.js
    source: |
      group.test('changing password', function (t) {

```
But, I can't catch what this message says. Can you give me a hint to get over this?

**Comment by gr2m** [comment]
looking into it

**Comment by gr2m** [comment]
The problem is [`delete response.result.meta`](https://github.com/Taekyoon/hoodie-account-server/blob/ad2c14136e92acdc96d0b3fca426375fbe1fb52a/tests/integration/routes/accounts/patch-accounts-test.js#L171) because `response.result` is null, so accessing `response.result.meta` throws an error. 

But I agree that there should be a better error message though, this one is not very helpful

**Comment by Taekyoon** [comment]
Oh now I see. I can catch it! When I delete this statement, it works well.
Can I delete `delete response.result.meta` because I feel it makes error?

**Comment by gr2m** [comment]
> Can I delete delete response.result.meta because I feel it makes error?

Yes, we don’t need it because response.result is empty for a 204 server response

**Pull request merged**
