### PR TITLE
WIP: test(routes): PATCH /accounts/123?include=profile

### PR DESCRIPTION
**Pull request by paulohp**
# PLEASE DO NOT MERGE YET, WORK IN PROGRESS

closes hoodiehq/camp#72

### CODE REVIEW

**Comment by gr2m** [comment]
@paulohp let us know if you need any help :)

**Comment by paulohp** [comment]
sure @gr2m, I'll get back on it later tonight :)

**Comment by gr2m** [comment]
how are things going? :) no pressure, just checking in

**Comment by gr2m** [comment]
Hey @paulohp the tests are currently failing. Do you want to finish up this PR?

**Comment by gr2m** [comment]
you nearly head it :) You only forgot to mock the requests to the CouchDB with this bit:

```js
    var couchdb = mockCouchDbUpdateAccountResponse()
      .reply(201, {
        ok: true,
        id: 'org.couchdb.user:pat-doe',
        rev: '2-3456'
      })
```

I fixed it up for you and will merge it in once the tests pass, thanks 👍

**Pull request merged**
