### PR TITLE
made changes to apiSessionsAdd

### PR DESCRIPTION
**Pull request by texassiga**

### CODE REVIEW

**Comment by hzoo** [comment]
In the Issue, it says:

> Commit the change docs(README): Constructor link in api.sessions.add()

So if you can, I would change the commit message - https://help.github.com/articles/changing-a-commit-message/

**Comment by gr2m** [comment]
so sorry to be so nitpicky, but can you change the commit message to 

> docs(README): Constructor link in api.sessions.add()

The `docs(README): ` prefix is important. We can also do it for you if you’re busy, just let us know :)

**Comment by texassiga** [comment]
Hey Gregor,
 Not a problem. I just made the change and pushed it. I don't remember if I have to do anything else at this point.

**Comment by gr2m** [comment]
Nope it’s perfect, thank you :) LGTM

**Comment by gr2m** [comment]
merged via 7a13510, thanks :th

**Pull request closed without merging**
