### PR TITLE
404 should be 401 on /session

### LINKED ISSUE #95: GET /session: 404 should be 401
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

The handler for the  [GET /session route](https://github.com/hoodiehq/hoodie-server-account/blob/61798c9/routes/session.js#L86-L133) currently returns 404 if a session is invalid.

### :dart: The goal

But in our [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/check-session) we define `401` as the error code for an invalid session, so the correct server response should be `401 Unauthorized – Session invalid`

### :clipboard: Step by Step

- [x] claim this issue (@hyperperforator)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] We currently test for a `404` status [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L60) and [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L104-L106). Replace it with `401`. Also: `.title` should be `'Unauthorized'` and add an assertion for `.detail` which must be `'Session invalid'`
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: GET /session: 404 should be 401`
- [x] Start a Pull Request.  Add `fixes #95` to the description.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L116-L118) and for comparison [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L62-L67)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix: GET /session: 404 should be 401`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by hyperperforator**
fixes #95 ✨

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM :+1: ping @hoodiehq/maintainers

**Comment by gr2m** [comment]
if you could rebase on latest master and squash the two `test: ...` commits into one, that’d be great :) Happy to help if you have questions how that works, or also happy to do it for you if you’re busy :)

**Comment by hyperperforator** [comment]
Hey @gr2m, I thought squashing miiiight be easy, but I'm not sure how to proceed since I've pushed them already. Any insight? :)

**Comment by HipsterBrown** [comment]
LGTM and will merge once the `test: ...` commits are squashed. 

@hyperperforator here is a nice intro to squashing commits from the command line -> https://davidwalsh.name/squash-commits-git

Instead of `git rebase -i master`, you should run `git rebase -i @~3`. The `@~3` tells git to look back at the last 3 commits. Then you should see the following:

```
pick 1ea353c test: GET /session: 404 should be 401
pick 5fb61ea test: GET /session: 404 should be 401
pick b75943b fix: GET /session: 404 should be 401
```

You can then use the `fixup` command to squash the 2nd `test` commit into the previous one. 

```
pick 1ea353c test: GET /session: 404 should be 401
fixup 5fb61ea test: GET /session: 404 should be 401
pick b75943b fix: GET /session: 404 should be 401
```

Then save the action by typing `:wq`, which will run the `rebase` (hopefully) without conflict. You can then "force" push the rebased branch by running `git push -f`. 

Let me know if you run into any issues.

**Comment by hyperperforator** [comment]
Ah, great tutorial @HipsterBrown – all done now! Thanks for the heads up, that was really helpful.

**Comment by HipsterBrown** [comment]
Since @gr2m and I have LGTM this before the rebase. I'll merge this asap.

**Comment by HipsterBrown** [comment]
Great work @hyperperforator! Thanks for this awesome contribution! :clap:

**Comment by hyperperforator** [comment]
Thanks for the help all, much appreciated that ya'll were patient and welcoming <3

**Comment by gr2m** [comment]
Thanks @hyperperforator :) We’ve invited you to the Hoodie Contributors Team, you should see an invitation on https://github.com/hoodiehq

Are you on twitter? We like giving shout outs to new contributors on https://twitter.com/hoodiehq if you don’t mind?

**Comment by hyperperforator** [comment]
Yay! Thanks @gr2m! Will keep my eye out for other places I can help. I'm 'ow' on Twitter, go for it, would love that!

**Comment by gr2m** [comment]
Done: https://twitter.com/hoodiehq/status/716997299445088256 :)
oh also if you like, come hang out with us in our chat :) http://hood.ie/chat

**Pull request merged**
